### ISSUE TITLE
CarrierBundleUtilities.dylib & gcrt1.o

### ISSUE THREAD

**Issue by doged** [doged/DOGED-iOS#1]
clang error: no such file or directory: CarrierBundleUtilities.dylib & gcrt1.o when attempting to run on simulator

@slayterdev

**Comment by doged** [comment]
what arm/sdk do i need? im using ios8.3 as a base

**Comment by SlayterDev** [comment]
The proper build settings should be setup in the Xcode project file. Beyond that, I'm not sure what those errors are.

**Comment by doged** [comment]
whats the latest version of xcode you've built this with?

**Comment by doged** [comment]
i tried 6.3.3 under osx 10.10 to no avail..

**Comment by SlayterDev** [comment]
I can't even remember. Haven't touched it in a year or so.
